const fs = require('fs');
const path = require('path');

async function createConfig(client, guildId) {
    const directoryPath = path.join(__dirname, '..', 'configs');
    const filePath = path.join(directoryPath, `${guildId}.json`);

    if (!fs.existsSync(filePath)) {
        try {
            const guild = client.guilds.cache.get(guildId);

            const highestRole = guild.roles.cache.reduce((prev, role) => (role.position > prev.position ? role : prev));

            const defaultData = {
                adminRole: highestRole.id,
                updateRoles: false,
                logChannel: null,
                logMessages: false,
                joinLeaveChannel: null,
                sendJoinLeaveMessages: false,
                joinMessage: 'Welcome to the server $user$!',
                leaveMessage: '$user$ has left the server.',
                ownerRole: null,
                chiefRole: null,
                strategistRole: null,
                captainRole: null,
                recruiterRole: null,
                recruitRole: null,
                allyOwnerRole: null,
                allyRole: null,
                championRole: null,
                heroRole: null,
                vipPlusRole: null,
                vipRole: null,
                vetRole: null,
                unverifiedRole: null,
                memberOfRole: null,
                levelRoles: {},
                chiefUpperThreshold: 730,
                chiefLowerThreshold: 365,
                strategistUpperThreshold: 50,
                strategistLowerThreshold: 30,
                captainUpperThreshold: 32,
                captainLowerThreshold: 16,
                recruiterUpperThreshold: 20,
                recruiterLowerThreshold: 10,
                recruitUpperThreshold: 20,
                recruitLowerThreshold: 10,
                levelRequirement: 100,
                extraTimeMultiplier: 1,
                averageRequirement: 5,
                newPlayerMinimumTime: 14,
                newPlayerThreshold: 5,
                guild: null,
                allies: [],
                trackedGuilds: [],
                chiefPromotionRequirement: ['NONE'],
                strategistPromotionRequirement: ['NONE'],
                captainPromotionRequirement: ['NONE'],
                recruiterPromotionRequirement: ['NONE'],
                chiefXPRequirement: 0,
                chiefLevelRequirement: 0,
                chiefContributorRequirement: 0,
                strategistXPRequirement: 0,
                strategistLevelRequirement: 0,
                strategistContributorRequirement: 0,
                captainXPRequirement: 0,
                captainLevelRequirement: 0,
                captainContributorRequirement: 0,
                recruiterXPRequirement: 0,
                recruiterLevelRequirement: 0,
                recruiterContributorRequirement: 0,
                warRole: null,
                tankRole: null,
                healerRole: null,
                damageRole: null,
                soloRole: null,
                warMessage: '',
                warClassMessage: '',
                promotionExceptions: {},
                demotionExceptions: {},
                warriorRole: null,
                fallenRole: null,
                battleMonkRole: null,
                paladinRole: null,
                mageRole: null,
                riftwalkerRole: null,
                lightBenderRole: null,
                arcanistRole: null,
                archerRole: null,
                sharpshooterRole: null,
                trapperRole: null,
                boltslingerRole: null,
                shamanRole: null,
                ritualistRole: null,
                summonerRole: null,
                acolyteRole: null,
                assassinRole: null,
                acrobatRole: null,
                shadestepperRole: null,
                tricksterRole: null,
                classMessage: '',
                classArchetypeMessage: '',
                chiefTimeRequirement: 0,
                strategistTimeRequirement: 0,
                captainTimeRequirement: 0,
                recruiterTimeRequirement: 0,
                administratorRole: null,
                moderatorRole: null,
                contentTeamRole: null,
                warLevelRequirement: 100,
                memberThreshold: 0.9,
                ecoRole: null,
                highRankChannel: null,
                chiefRequirementsCount: 5,
                strategistRequirementsCount: 4,
                captainRequirementsCount: 3,
                recruiterRequirementsCount: 1,
                inactivityExceptions: {},
                chiefOptionalTimeRequirement: 0,
                chiefWarsRequirement: 0,
                chiefWeeklyPlaytimeRequirement: 0,
                chiefWarBuildRequirement: false,
                chiefEcoRequirement: false,
                strategistOptionalTimeRequirement: 0,
                strategistWarsRequirement: 0,
                strategistWeeklyPlaytimeRequirement: 0,
                strategistWarBuildRequirement: false,
                strategistEcoRequirement: false,
                captainOptionalTimeRequirement: 0,
                captainWarsRequirement: 0,
                captainWeeklyPlaytimeRequirement: 0,
                captainWarBuildRequirement: false,
                captainEcoRequirement: false,
                recruiterOptionalTimeRequirement: 0,
                recruiterWarsRequirement: 0,
                recruiterWeeklyPlaytimeRequirement: 0,
                recruiterWarBuildRequirement: false,
                recruiterEcoRequirement: false,
                guildEventsMessage: '',
                giveawayRole: null,
                chiefPromotions: [],
                eventsRole: null,
                addGuildPrefixes: true,
                bannedPlayers: [],
            };

            await fs.writeFile(filePath, JSON.stringify(defaultData, null, 2));
            console.log(`Created config file for guild ${guildId}`);
        } catch (err) {
            console.error(`Error creating config file for guild ${guildId}: ${err}`);
        }
    } else {
        console.error('createConfig called but config exists');
    }
}

module.exports = createConfig;
