// Types of messages that can have a choice button
// Eg. 2 guilds with same tag
const MessageType = {
  ACTIVE_HOURS: 'ACTIVE_HOURS',
  ADD_DEMOTION_EXCEPTION: 'ADD_DEMOTION_EXCEPTION',
  ADD_INACTIVITY_EXCEPTION: 'ADD_INACTIVITY_EXCEPTION',
  ADD_PROMOTION_EXCEPTION: 'ADD_PROMOTION_EXCEPTION',
  ADD_ALLY: 'ADD_ALLY',
  GUILD_STATS: 'GUILD_STATS',
  LAST_LOGINS: 'LAST_LOGINS',
  ONLINE: 'ONLINE',
  PROMOTION_PROGRESS: 'PROMOTION_PROGRESS',
  REGISTER_USER: 'REGISTER_USER',
  REMOVE_ALLY: 'REMOVE_ALLY',
  REMOVE_DEMOTION_EXCEPTION: 'REMOVE_DEMOTION_EXCEPTION',
  REMOVE_INACTIVITY_EXCEPTION: 'REMOVE_INACTIVITY_EXCEPTION',
  REMOVE_PROMOTION_EXCEPTION: 'REMOVE_PROMOTION_EXCEPTION',
  SET_GUILD: 'SET_GUILD',
  SUS: 'SUS',
  TRACK_GUILD: 'TRACK_GUILD',
  UNTRACK_GUILD: 'UNTRACK_GUILD',
  UPDATE_GUILD: 'UPDATE_GUILD',
  UPDATE_PLAYER: 'UPDATE_PLAYER',
  VERIFY: 'VERIFY',
  WORLD_ACTIVITY: 'WORLD_ACTIVITY',
};

module.exports = MessageType;
